"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os

def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()

APP = ['src/main.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
	name="Bad Player",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'PyQt5', 'sqlalchemy', 'pyyaml', 'eyed3'],
    # packages=['PyQt5', 'sqlalchemy', 'pyyaml'],
    author = "Sébastien Treille",
    author_email = "c2ViYXN0aWVudHJlaWxsZUBnbWFpbC5jb20=",
    description = ("A bad player that play good playlists !"),
    long_description=read('README.md'),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Topic :: Utilities",
    ],
)
