# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.videoframe = QtWidgets.QFrame(self.centralwidget)
        self.videoframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoframe.setObjectName("videoframe")
        self.verticalLayout.addWidget(self.videoframe)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.positionSlider = QtWidgets.QSlider(self.centralwidget)
        self.positionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.positionSlider.setObjectName("positionSlider")
        self.verticalLayout_2.addWidget(self.positionSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_4.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.volumeSlider = QtWidgets.QSlider(self.centralwidget)
        self.volumeSlider.setMinimumSize(QtCore.QSize(50, 0))
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_4.addWidget(self.volumeSlider)
        self.showHideButton = QtWidgets.QPushButton(self.centralwidget)
        self.showHideButton.setObjectName("showHideButton")
        self.horizontalLayout_4.addWidget(self.showHideButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.playlistTable = QtWidgets.QTableWidget(self.centralwidget)
        self.playlistTable.setMinimumSize(QtCore.QSize(200, 0))
        self.playlistTable.setMaximumSize(QtCore.QSize(200, 16777215))
        self.playlistTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playlistTable.setObjectName("playlistTable")
        self.playlistTable.setColumnCount(0)
        self.playlistTable.setRowCount(0)
        self.playlistTable.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.playlistTable)
        self.songTable = QtWidgets.QTableWidget(self.centralwidget)
        self.songTable.setMinimumSize(QtCore.QSize(200, 0))
        self.songTable.setMaximumSize(QtCore.QSize(200, 16777215))
        self.songTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.songTable.setObjectName("songTable")
        self.songTable.setColumnCount(0)
        self.songTable.setRowCount(0)
        self.songTable.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.songTable)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAddPlaylist = QtWidgets.QAction(MainWindow)
        self.actionAddPlaylist.setObjectName("actionAddPlaylist")
        self.actionAddMusicFromFile = QtWidgets.QAction(MainWindow)
        self.actionAddMusicFromFile.setObjectName("actionAddMusicFromFile")
        self.actionAddMusicFromYoutube = QtWidgets.QAction(MainWindow)
        self.actionAddMusicFromYoutube.setObjectName("actionAddMusicFromYoutube")
        self.actionAddMusicFromSoundcloud = QtWidgets.QAction(MainWindow)
        self.actionAddMusicFromSoundcloud.setObjectName("actionAddMusicFromSoundcloud")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAddPlaylist)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAddMusicFromFile)
        self.menuFile.addAction(self.actionAddMusicFromYoutube)
        self.menuFile.addAction(self.actionAddMusicFromSoundcloud)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "1:56:42 / 2:26:42"))
        self.showHideButton.setText(_translate("MainWindow", "Hide"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionAddPlaylist.setText(_translate("MainWindow", "Add playlist"))
        self.actionAddMusicFromFile.setText(_translate("MainWindow", "Add music from file"))
        self.actionAddMusicFromYoutube.setText(_translate("MainWindow", "Add music from Youtube"))
        self.actionAddMusicFromSoundcloud.setText(_translate("MainWindow", "Add music from Soundcloud"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

